#This playbbok will install HTTP server and start the server.
---
- hosts: all
  remote_user: root
  tasks:
    - name: Copy index file 
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
        mode: push
        owner: apache
        group: apache
              
    - name: Start HTTP Server
      service: name=httpd enabled=yes state=restarted
    
