---
- hosts: all
  become: true
  tasks:
  - name: Date and Time Display
    debug:
      var=ansible_date_time.date
  - name: Date and Time Example in Ansible
    debug:
      var=ansible_date_time.time
  - name: Timestamp example with file
    command: touch helloworld{{ansible_date_time.date}}.log
