---                                                                                                                               
- name: deploy vsftpd
  hosts: all
  tasks: 
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: create readme file
    copy: 
      content: "Hi Subscribers type yaml files instead of copying"
      dest: /var/ftp/pub/readme
      force: no
      mode: 0444
...
