---
- name: Sync Pull task - Executed on  the Destination hosts
  hosts: all
  user: ansible
  tasks:   
    - name: Copy the file from node1 to node2 using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: all
      register: syncfile
      run_once: true
      with_items:
       - "/tmp/gradle-wrapper.jar"
