---
- name: Transfer and execute a script.
  hosts: all
  remote_user: ansible
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=hcscript.sh dest=/home/ansible mode=0777
 
     - name: Execute the script
       command: sh /home/ansible/hcscript.sh
       register: output

     - debug: var=output.stdout_lines
