---
- name: Sync Pull task - Executed on  the Destination host "{{groups['appgrp'][1]}}"
  hosts: "{{groups['appgrp'][0]}}"
  user: ansible
  tasks:   
    - name: Copy the file from mwiapp01 to mwiapp02 using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{groups['appgrp'][1]}}"
      register: syncfile
      run_once: true
      with_items:
       - "/tmp/gradle-wrapper.jar"
