---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  hosts: all
  tasks:
     - name: Transfer executable script script
       copy: src=/home/ansible/hcscript.sh dest=/opt/ mode=0777
     - name: Execute the script
       command: sh /opt/hcscript.sh
       register: output
       debug: var=output.stdout_lines
