---
  # Play1 - WebServer related tasks
  - name: Play Web - Create apache directories and username in web servers
    hosts: all
    become: yes
    tasks:
      - name: create username apacheadm
        user:
          name: apacheadm
          shell: /bin/bash
          home: /home/apacheadm

      - name: install httpd
        yum:
          name: httpd
          state: installed
        
  # Play2 - Application Server related tasks
  - name: Play app - Create tomcat directories and username in app servers
    hosts: all
    become: yes
    tasks:
      - name: Create a username for tomcat
        user:
          name: tomcatadm
          shell: /bin/bash
          home: /home/tomcat

      - name: create a directory for apache tomcat
        file:
          path: /opt/oracle
          owner: tomcatadm
          state: present
          mode: 0755
